# generated by configure / remove this line to disable regeneration
prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/Users/davidrogers/Documents/Development/Ogre/iPhoneDependencies/zziplib/Darwin_10.4.0_i386.d/zzip/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/Users/davidrogers/Documents/Development/Ogre/iPhoneDependencies/zziplib/Darwin_10.4.0_i386.d/.."
package="zziplib"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "zziplib"
;; --help) pkg-config --help ; echo Buildscript Of "ZZipLib - libZ-based ZIP-access Library"
;; --modversion|--version) echo "0.13.59"
;; --requires) echo pkg-config zzip-zlib-config "zzip-zlib-config"
;; --libs) echo -L${libdir} "" "-lzzip"
pkg-config zzip-zlib-config
;; --cflags) echo -I${includedir} ""
pkg-config zzip-zlib-config
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
